language: java
jdk:
  # do stuff with Java 8
  - oraclejdk8
  # do stuff with open Java 8
  - openjdk8

script:
  # do stuff with Java 8
  - jdk_switcher use oraclejdk8
  - mvn clean verify test
  # do stuff with open Java 8
  - jdk_switcher use openjdk8
  - mvn clean verify test
